llm:
  provider: "ollama"
  model: "llama3.1:8b"
  max_attempts: 4
  grader_model: "llama3.1:8b" 
  temperature: 0
  max_tokens: 200000
  timeout: 240
  models_to_pull:  # List of models to pull on startup
    - "llama3.1:8b"
    - "llama3.2:1b"
    # Add any other models needed
    # - "mistral:7b"
    # - "qwen:72b"
    #- "llama3.1:70b"


vectorstore:
  model_name: "Alibaba-NLP/gte-large-en-v1.5"
  collection_name: "vulnerabilities"
  persistent_dir: "./chromadb"
  num_docs: 5

tavily:
  api_key: ""

huggingface:
  api_token: ""
  model_name: "Alibaba-NLP/gte-large-en-v1.5"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  datefmt: "%Y-%m-%d %H:%M:%S"