version: '3.8'

services:
  staf-api:
    build: 
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    volumes:
      - .:/app
      - ./chromadb:/app/chromadb
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - ${CONFIG_PATH:-./config.yaml}:/app/config.yaml 
    environment:
      - PYTHONPATH=/app
      - NVIDIA_VISIBLE_DEVICES=all
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - HF_TOKEN=${HF_TOKEN}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - HF_HOME=/app/.cache/huggingface
      - TRANSFORMERS_OFFLINE=0
      - HF_DATASETS_OFFLINE=0
      - CURL_VERBOSE=1
    depends_on:
      - ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ollama:
    image: ollama/ollama
    runtime: nvidia
    network_mode: "host"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama:
